metadata.format.version = "1.1"

[versions]

paper = "1.21.8-R0.1-SNAPSHOT"

runtask = "3.0.0"

miniplaceholders = "3.0.0-SNAPSHOT"
adventure = "4.14.0"
insights = "6.15.0"

[libraries]

paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }

insights = { module = "dev.frankheijden.insights:Insights", version.ref = "insights" }

[plugins]

runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
runpaper = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
