name: Insights-Expansion
version: '${version}'
author: 4drian3d
main: io.github.miniplaceholders.expansion.insights.PaperPlugin
api-version: '1.19'
folia-supported: true
dependencies:
  server:
    MiniPlaceholders:
      required: true
    Insights:
      required: true
